version: "3.8"

x-bench-volumes: &bench-volumes
  volumes:
    - sites:/home/frappe/frappe-bench/sites
    - logs:/home/frappe/frappe-bench/logs

services:

  backend:
    build: .
    <<: *bench-volumes
    restart: unless-stopped
    command: >
      bash -c "bench set-config -g db_host db &&
      bench set-config -gp db_port 3306 &&
      bench set-config -g redis_cache redis://redis-cache:6379 &&
      bench set-config -g redis_queue redis://redis-queue:6379 &&
      bench set-config -g redis_socketio redis://redis-socketio:6379 &&
      bench set-config -gp socketio_port 9000 &&
      /home/frappe/frappe-bench/env/bin/gunicorn --chdir=/home/frappe/frappe-bench/sites --bind=0.0.0.0:8000 --timeout=120 --workers=2 frappe.app:application"
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
      redis-socketio:
        condition: service_started
        
  queue-short:
    build: .
    <<: *bench-volumes
    restart: unless-stopped
    command: bench worker --queue short,default
    depends_on:
      - backend

  queue-long:
    build: .
    <<: *bench-volumes
    restart: unless-stopped
    command: bench worker --queue long,default,short
    depends_on:
      - backend

  scheduler:
    build: .
    <<: *bench-volumes
    restart: unless-stopped
    command: bench schedule
    depends_on:
      - backend

  websocket:
    build: .
    <<: *bench-volumes
    restart: unless-stopped
    command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      - backend

  frontend:
    build: .
    restart: unless-stopped
    command: nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: erp.drimysgin.com
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
      HTTP_PORT: 8181
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      
    ports:
      - "8181:8181"
    depends_on:
      - backend
      - websocket

  db:
    image: mariadb:10.6
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=changeme_strong"]
      interval: 5s
      retries: 20
    environment:
      MYSQL_ROOT_PASSWORD: changeme_strong
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped

  redis-queue:
    image: redis:7-alpine
    restart: unless-stopped

  redis-socketio:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  db-data:
  sites:
  logs:
